services:
  postgres:
    image: postgres:16    # the image tag we want to use for the service


    environment:
    # here we can define environment variablesin which to create the default user, password and database. 
    POSTGRES_DB: example_db
    POSTGRES_DB_USER: pg_admin
    POSTGRES_DB_PASSWORD: example_password
    ports:
    # here you will list the port we want to map inside the container, and the port we want to expose it on in the host
    ports:
      - "5432:5432"
    volumes: 
     # list any volumes (filesystem/drive mounts) that you want to map to a location inside the container  
     # for instance, any .sql files you mount in a directory to the /docker-entrypoint-initdb.d location in the container
     # will automatically be run on startup
      volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro #mount the init script and make it read only(ro)
        
      # The above line is initially built in the project to show concept and test connection but could be used as project sees fit